## Web scraping de IMDB

Descarga la información correspondiente y guarda en un csv el top de las 250 películas mediante webscraping. Encapsúlalo en un script.

Obtén:
* Título
* Año
* Duración
* Posición
* Rating

In [55]:
pip install cloudscraper

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cloudscraper in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.71)
Requirement already satisfied: pyparsing>=2.4.7 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cloudscraper) (3.3.2)
Requirement already satisfied: requests>=2.9.2 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cloudscraper) (2.33.1)
Requirement already satisfied: requests-toolbelt>=0.9.1 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.9.2->cloudscraper) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.9.2->cloudscraper) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.9.2->cloudscraper) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\jvazq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.9.2->cloudscraper) (2026.4.22)
Note: you may need to restart the kernel to use updated packages.

In [56]:
import pandas as pd
import json
from bs4 import BeautifulSoup
import undetected_chromedriver as uc
import time

url = "https://www.imdb.com/chart/top/"

driver = uc.Chrome(
    browser_executable_path=r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    headless=False,
    version_main=147
)

driver.get(url)
time.sleep(5)

html = driver.page_source
soup = BeautifulSoup(html, "html.parser")
print(soup.title)

<title>Las 250 mejores películas de IMDb</title>

In [57]:
print(html[:2000])

<html lang="es-ES" xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml"><head><script async="" src="https://sb.scorecardresearch.com/beacon.js"></script><script async="" src="https://images-na.ssl-images-amazon.com/images/I/215h87l68bL.js" crossorigin="anonymous"></script><meta charset="utf-8"><meta name="viewport" content="width=device-width"><script>if(typeof uet === 'function'){ uet('bb', 'LoadTitle', {wb: 1}); }</script><title>Las 250 mejores películas de IMDb</title><meta name="description" content="Según la calificación de los votantes habituales de IMDb." data-id="main"><meta name="google-site-verification" content="0cadf7898134e79b"><meta name="msvalidate.01" content="C1DACEF2769068C0B0D2687C9E5105FA"><meta name="robots" content="max-image-preview:large"><meta property="og:url" content="https://www.imdb.com/es-es/chart/top/"><meta property="og:site_name" content="IMDb"><meta property="og:title" content="Las 250 mejores películas de IMDb"><meta property="og:description" content="Según la calificación de los votantes habituales de IMDb."><meta property="og:type" content="website"><meta property="og:image" content="https://m.media-amazon.com/images/G/01/imdb/images/social/imdb_logo.png"><meta property="og:image:height" content="1000"><meta property="og:image:width" content="1000"><meta content="es_ES" property="og:locale"><meta content="en_US" property="og:locale:alternate"><meta content="es_MX" property="og:locale:alternate"><meta content="fr_FR" property="og:locale:alternate"><meta content="fr_CA" property="og:locale:alternate"><meta content="it_IT" property="og:locale:alternate"><meta content="pt_BR" property="og:locale:alternate"><meta content="hi_IN" property="og:locale:alternate"><meta content="de_DE" property="og:locale:alternate"><meta property="twitter:site" content="@IMDb"><meta property="twitter:title" content="Las 250 mejores películas de IMDb"><meta property="twitter:description" content="Según la calificació

In [58]:
n = 0
for x in soup.find_all("h3", class_="ipc-title__text"):
    print(x)
    n += 1
    print(n)

<h3 class="ipc-title__text">Cadena perpetua</h3>
1
<h3 class="ipc-title__text">El padrino</h3>
2
<h3 class="ipc-title__text">El caballero oscuro</h3>
3
<h3 class="ipc-title__text">El padrino parte II</h3>
4
<h3 class="ipc-title__text">12 hombres sin piedad</h3>
5
<h3 class="ipc-title__text">El señor de los anillos: El retorno del rey</h3>
6
<h3 class="ipc-title__text">La lista de Schindler</h3>
7
<h3 class="ipc-title__text">El señor de los anillos: La comunidad del anillo</h3>
8
<h3 class="ipc-title__text">Pulp Fiction</h3>
9
<h3 class="ipc-title__text">El bueno, el feo y el malo</h3>
10
<h3 class="ipc-title__text">El señor de los anillos: Las dos torres</h3>
11
<h3 class="ipc-title__text">Forrest Gump</h3>
12
<h3 class="ipc-title__text">El club de la lucha</h3>
13
<h3 class="ipc-title__text">Origen</h3>
14
<h3 class="ipc-title__text">El imperio contraataca</h3>
15
<h3 class="ipc-title__text">Matrix</h3>
16
<h3 class="ipc-title__text">Uno de los nuestros</h3>
17
<h3 class="ipc-title__text">Interstellar</h3>
18
<h3 class="ipc-title__text">Alguien voló sobre el nido del cuco</h3>
19
<h3 class="ipc-title__text">Seven</h3>
20
<h3 class="ipc-title__text">Qué bello es vivir</h3>
21
<h3 class="ipc-title__text">El silencio de los corderos</h3>
22
<h3 class="ipc-title__text">Los siete samuráis</h3>
23
<h3 class="ipc-title__text">Salvar al soldado Ryan</h3>
24
<h3 class="ipc-title__text">La milla verde</h3>
25
<h3 class="ipc-title__text">Ciudad de Dios</h3>
26
<h3 class="ipc-title__text">La vida es bella</h3>
27
<h3 class="ipc-title__text">Terminator 2: El juicio final</h3>
28
<h3 class="ipc-title__text">Regreso al futuro</h3>
29
<h3 class="ipc-title__text">La guerra de las galaxias</h3>
30
<h3 class="ipc-title__text">El viaje de Chihiro</h3>
31
<h3 class="ipc-title__text">El pianista</h3>
32
<h3 class="ipc-title__text">Gladiator (El gladiador)</h3>
33
<h3 class="ipc-title__text">Parásitos</h3>
34
<h3 class="ipc-title__text">Kill Bill: The Whole Bloody Affair</h3>
35
<h3 class="ipc-title__text">La tumba de las luciérnagas</h3>
36
<h3 class="ipc-title__text">Psicosis</h3>
37
<h3 class="ipc-title__text">El rey león</h3>
38
<h3 class="ipc-title__text">Harakiri</h3>
39
<h3 class="ipc-title__text">Infiltrados</h3>
40
<h3 class="ipc-title__text">Whiplash</h3>
41
<h3 class="ipc-title__text">El truco final (El prestigio)</h3>
42
<h3 class="ipc-title__text">American History X</h3>
43
<h3 class="ipc-title__text">El profesional (Léon)</h3>
44
<h3 class="ipc-title__text">Spider-Man: Cruzando el multiverso</h3>
45
<h3 class="ipc-title__text">Cinema Paradiso</h3>
46
<h3 class="ipc-title__text">Casablanca</h3>
47
<h3 class="ipc-title__text">Intocable</h3>
48
<h3 class="ipc-title__text">Sospechosos habituales</h3>
49
<h3 class="ipc-title__text">Django desencadenado</h3>
50
<h3 class="ipc-title__text">Alien, el octavo pasajero</h3>
51
<h3 class="ipc-title__text">La ventana indiscreta</h3>
52
<h3 class="ipc-title__text">Tiempos modernos</h3>
53
<h3 class="ipc-title__text">Hasta que llegó su hora</h3>
54
<h3 class="ipc-title__text">Luces de la ciudad</h3>
55
<h3 class="ipc-title__text">Apocalypse Now</h3>
56
<h3 class="ipc-title__text">WALL·E</h3>
57
<h3 class="ipc-title__text">Memento</h3>
58
<h3 class="ipc-title__text">Dune: Parte dos</h3>
59
<h3 class="ipc-title__text">Vengadores: Infinity War</h3>
60
<h3 class="ipc-title__text">En busca del arca perdida</h3>
61
<h3 class="ipc-title__text">La vida de los otros</h3>
62
<h3 class="ipc-title__text">Spider-Man: Un nuevo universo</h3>
63
<h3 class="ipc-title__text">El crepúsculo de los dioses</h3>
64
<h3 class="ipc-title__text">Testigo de cargo</h3>
65
<h3 class="ipc-title__text">Senderos de gloria</h3>
66
<h3 class="ipc-title__text">El resplandor</h3>
67
<h3 class="ipc-title__text">El gran dictador</h3>
68
<h3 class="ipc-title__text">Malditos bastardos</h3>
69
<h3 class="ipc-title__text">12th Fail</h3>
70
<h3 class="ipc-title__text">Aliens: El regreso</h3>
71
<h3 class="ipc-title__text">El infierno del odio</h3>
72
<h3 class="ipc-title__text">Vengadores: Endgame</h3>
73
<h3 class="ipc-title__text">El indomable Will Hunting</h3>
74
<h3 class="ipc-title__text">El caballero oscuro: La leyenda renace</h3>
75
<h3 class="ipc-title__text">Coco</h3>
76
<h3 class="ipc-title__text">Amadeus</h3>
77
<h3 class="ipc-title__text">Toy Story</h3>
78
<h3 class="ipc-title__text">Your Name.</h3>
79
<h3 class="ipc-title__text">El submarino (Das Boot)</h3>
80
<h3 class="ipc-title__text">Braveheart</h3>
81
<h3 class="ipc-title__text">Old Boy</h3>
82
<h3 class="ipc-title__text">La princesa Mononoke</h3>
83
<h3 class="ipc-title__text">Teléfono rojo: volamos hacia Moscú</h3>
84
<h3 class="ipc-title__text">3 Idiots</h3>
85
<h3 class="ipc-title__text">American Beauty</h3>
86
<h3 class="ipc-title__text">Cafarnaúm</h3>
87
<h3 class="ipc-title__text">Cantando bajo la lluvia</h3>
88
<h3 class="ipc-title__text">Joker</h3>
89
<h3 class="ipc-title__text">Érase una vez en América</h3>
90
<h3 class="ipc-title__text">El retorno del jedi</h3>
91
<h3 class="ipc-title__text">Masacre (Ven y mira)</h3>
92
<h3 class="ipc-title__text">Réquiem por un sueño</h3>
93
<h3 class="ipc-title__text">Toy Story 3</h3>
94
<h3 class="ipc-title__text">Vivir</h3>
95
<h3 class="ipc-title__text">La caza de Thomas Vinterberg</h3>
96
<h3 class="ipc-title__text">Incendios</h3>
97
<h3 class="ipc-title__text">¡Olvídate de mí!</h3>
98
<h3 class="ipc-title__text">El apartamento</h3>
99
<h3 class="ipc-title__text">Lawrence de Arabia</h3>
100
<h3 class="ipc-title__text">Heat</h3>
101
<h3 class="ipc-title__text">El precio del poder</h3>
102
<h3 class="ipc-title__text">Reservoir Dogs</h3>
103
<h3 class="ipc-title__text">2001: Una odisea del espacio</h3>
104
<h3 class="ipc-title__text">Proyecto Salvación</h3>
105
<h3 class="ipc-title__text">Up</h3>
106
<h3 class="ipc-title__text">Perdición</h3>
107
<h3 class="ipc-title__text">Con la muerte en los talones</h3>
108
<h3 class="ipc-title__text">Taare Zameen Par</h3>
109
<h3 class="ipc-title__text">La chaqueta metálica</h3>
110
<h3 class="ipc-title__text">M, el vampiro de Düsseldorf</h3>
111
<h3 class="ipc-title__text">Amélie</h3>
112
<h3 class="ipc-title__text">Ciudadano Kane</h3>
113
<h3 class="ipc-title__text">De entre los muertos (Vertigo)</h3>
114
<h3 class="ipc-title__text">Nader y Simin, una separación</h3>
115
<h3 class="ipc-title__text">Jungla de cristal</h3>
116
<h3 class="ipc-title__text">Matar a un ruiseñor</h3>
117
<h3 class="ipc-title__text">Indiana Jones y la última cruzada</h3>
118
<h3 class="ipc-title__text">El golpe</h3>
119
<h3 class="ipc-title__text">La naranja mecánica</h3>
120
<h3 class="ipc-title__text">Metrópolis</h3>
121
<h3 class="ipc-title__text">1917</h3>
122
<h3 class="ipc-title__text">Snatch. Cerdos y diamantes</h3>
123
<h3 class="ipc-title__text">El lobo de Wall Street</h3>
124
<h3 class="ipc-title__text">El hundimiento</h3>
125
<h3 class="ipc-title__text">L.A. Confidential</h3>
126
<h3 class="ipc-title__text">El show de Truman</h3>
127
<h3 class="ipc-title__text">Incontrolable</h3>
128
<h3 class="ipc-title__text">Dangal</h3>
129
<h3 class="ipc-title__text">Ladrón de bicicletas</h3>
130
<h3 class="ipc-title__text">Green Book</h3>
131
<h3 class="ipc-title__text">Shutter Island</h3>
132
<h3 class="ipc-title__text">Oppenheimer</h3>
133
<h3 class="ipc-title__text">Vencedores o vencidos</h3>
134
<h3 class="ipc-title__text">Batman Begins</h3>
135
<h3 class="ipc-title__text">Hamilton</h3>
136
<h3 class="ipc-title__text">La muerte tenía un precio</h3>
137
<h3 class="ipc-title__text">Jurassic Park (Parque Jurásico)</h3>
138
<h3 class="ipc-title__text">Taxi Driver</h3>
139
<h3 class="ipc-title__text">Con faldas y a lo loco</h3>
140
<h3 class="ipc-title__text">Pozos de ambición</h3>
141
<h3 class="ipc-title__text">El padre</h3>
142
<h3 class="ipc-title__text">El chico</h3>
143
<h3 class="ipc-title__text">Eva al desnudo</h3>
144
<h3 class="ipc-title__text">El sexto sentido</h3>
145
<h3 class="ipc-title__text">Ran</h3>
146
<h3 class="ipc-title__text">Casino</h3>
147
<h3 class="ipc-title__text">Attack on Titan: The Last Attack</h3>
148
<h3 class="ipc-title__text">No es país para viejos</h3>
149
<h3 class="ipc-title__text">La cosa (El enigma de otro mundo)</h3>
150
<h3 class="ipc-title__text">Prisioneros</h3>
151
<h3 class="ipc-title__text">Top Gun: Maverick</h3>
152
<h3 class="ipc-title__text">Kill Bill: Volumen 1</h3>
153
<h3 class="ipc-title__text">El laberinto del fauno</h3>
154
<h3 class="ipc-title__text">Sin perdón</h3>
155
<h3 class="ipc-title__text">Una mente maravillosa</h3>
156
<h3 class="ipc-title__text">El castillo ambulante</h3>
157
<h3 class="ipc-title__text">El tesoro de Sierra Madre</h3>
158
<h3 class="ipc-title__text">Buscando a Nemo</h3>
159
<h3 class="ipc-title__text">Klaus</h3>
160
<h3 class="ipc-title__text">Yojimbo</h3>
161
<h3 class="ipc-title__text">La gran evasión</h3>
162
<h3 class="ipc-title__text">El hombre elefante</h3>
163
<h3 class="ipc-title__text">Los caballeros de la mesa cuadrada y sus locos seguidores</h3>
164
<h3 class="ipc-title__text">Guardianes de la noche: Kimetsu no Yaiba - La fortaleza infinita</h3>
165
<h3 class="ipc-title__text">Crimen perfecto</h3>
166
<h3 class="ipc-title__text">El secreto de sus ojos</h3>
167
<h3 class="ipc-title__text">Lo que el viento se llevó</h3>
168
<h3 class="ipc-title__text">La mejor juventud</h3>
169
<h3 class="ipc-title__text">Lock &amp; Stock</h3>
170
<h3 class="ipc-title__text">Chinatown</h3>
171
<h3 class="ipc-title__text">V de vendetta</h3>
172
<h3 class="ipc-title__text">Atrápame si puedes</h3>
173
<h3 class="ipc-title__text">Del revés (Inside Out)</h3>
174
<h3 class="ipc-title__text">Rashomon</h3>
175
<h3 class="ipc-title__text">Trainspotting</h3>
176
<h3 class="ipc-title__text">Tres anuncios en las afueras</h3>
177
<h3 class="ipc-title__text">El puente sobre el río Kwai</h3>
178
<h3 class="ipc-title__text">El club de los poetas muertos</h3>
179
<h3 class="ipc-title__text">Harry Potter y las Reliquias de la Muerte: Parte 2</h3>
180
<h3 class="ipc-title__text">Robot salvaje</h3>
181
<h3 class="ipc-title__text">Barry Lyndon</h3>
182
<h3 class="ipc-title__text">Warrior</h3>
183
<h3 class="ipc-title__text">Ben-Hur</h3>
184
<h3 class="ipc-title__text">Fargo</h3>
185
<h3 class="ipc-title__text">Million Dollar Baby</h3>
186
<h3 class="ipc-title__text">Mad Max: Furia en la carretera</h3>
187
<h3 class="ipc-title__text">Hasta el último hombre (Hacksaw Ridge)</h3>
188
<h3 class="ipc-title__text">Children of Heaven</h3>
189
<h3 class="ipc-title__text">Toro salvaje</h3>
190
<h3 class="ipc-title__text">Mi vecino Totoro</h3>
191
<h3 class="ipc-title__text">Gran Torino</h3>
192
<h3 class="ipc-title__text">Ratatouille</h3>
193
<h3 class="ipc-title__text">12 años de esclavitud</h3>
194
<h3 class="ipc-title__text">El gran hotel Budapest</h3>
195
<h3 class="ipc-title__text">Antes de amanecer</h3>
196
<h3 class="ipc-title__text">Memories of Murder (Crónica de un asesino en serie)</h3>
197
<h3 class="ipc-title__text">Cómo entrenar a tu dragón</h3>
198
<h3 class="ipc-title__text">Blade Runner</h3>
199
<h3 class="ipc-title__text">Perdida</h3>
200
<h3 class="ipc-title__text">Monstruos, S.A.</h3>
201
<h3 class="ipc-title__text">Spider-Man: No Way Home</h3>
202
<h3 class="ipc-title__text">Hababam Sinifi: Sinifta Kaldi</h3>
203
<h3 class="ipc-title__text">Tiburón</h3>
204
<h3 class="ipc-title__text">Le Mans '66</h3>
205
<h3 class="ipc-title__text">En el nombre del padre</h3>
206
<h3 class="ipc-title__text">Relatos salvajes</h3>
207
<h3 class="ipc-title__text">La quimera del oro</h3>
208
<h3 class="ipc-title__text">El moderno Sherlock Holmes</h3>
209
<h3 class="ipc-title__text">Mary and Max</h3>
210
<h3 class="ipc-title__text">El cazador</h3>
211
<h3 class="ipc-title__text">El salario del miedo</h3>
212
<h3 class="ipc-title__text">El maquinista de La General</h3>
213
<h3 class="ipc-title__text">Rocky</h3>
214
<h3 class="ipc-title__text">Logan</h3>
215
<h3 class="ipc-title__text">Caballero sin espada</h3>
216
<h3 class="ipc-title__text">Piratas del Caribe: La maldición de la Perla Negra</h3>
217
<h3 class="ipc-title__text">A Silent Voice: The Movie</h3>
218
<h3 class="ipc-title__text">Cuentos de Tokio</h3>
219
<h3 class="ipc-title__text">La ley del silencio</h3>
220
<h3 class="ipc-title__text">El odio</h3>
221
<h3 class="ipc-title__text">Spotlight</h3>
222
<h3 class="ipc-title__text">Fresas salvajes</h3>
223
<h3 class="ipc-title__text">Chainsaw Man - La película: El arco de Reze</h3>
224
<h3 class="ipc-title__text">Sonrisas y lágrimas</h3>
225
<h3 class="ipc-title__text">Terminator</h3>
226
<h3 class="ipc-title__text">Maharaja</h3>
227
<h3 class="ipc-title__text">Jai Bhim</h3>
228
<h3 class="ipc-title__text">El tercer hombre</h3>
229
<h3 class="ipc-title__text">El gran Lebowski</h3>
230
<h3 class="ipc-title__text">Los mejores años de nuestra vida</h3>
231
<h3 class="ipc-title__text">Antes del atardecer</h3>
232
<h3 class="ipc-title__text">La habitación</h3>
233
<h3 class="ipc-title__text">El séptimo sello</h3>
234
<h3 class="ipc-title__text">Los Increíbles</h3>
235
<h3 class="ipc-title__text">Hotel Rwanda</h3>
236
<h3 class="ipc-title__text">Siempre a tu lado (Hachiko)</h3>
237
<h3 class="ipc-title__text">Platoon</h3>
238
<h3 class="ipc-title__text">El exorcista</h3>
239
<h3 class="ipc-title__text">El gigante de hierro</h3>
240
<h3 class="ipc-title__text">Rush</h3>
241
<h3 class="ipc-title__text">Cuenta conmigo</h3>
242
<h3 class="ipc-title__text">El mago de Oz</h3>
243
<h3 class="ipc-title__text">Mi padre y mi hijo</h3>
244
<h3 class="ipc-title__text">La batalla de Argel</h3>
245
<h3 class="ipc-title__text">La pasión de Juana de Arco</h3>
246
<h3 class="ipc-title__text">La doncella</h3>
247
<h3 class="ipc-title__text">Network, un mundo implacable</h3>
248
<h3 class="ipc-title__text">Drishyam</h3>
249
<h3 class="ipc-title__text">Milagro en la celda 7</h3>
250
<h3 class="ipc-title__text">Información sobre gráficos</h3>
251
<h3 class="ipc-title__text">Más por descubrir</h3>
252
<h3 class="ipc-title__text">Gráficos populares</h3>
253
<h3 class="ipc-title__text">Noticias sobre películas<svg class="ipc-icon ipc-icon--chevron-right-inline ipc-icon--inline ipc-title-link ipc-title-link-chevron" fill="currentColor" height="24" role="presentation" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M5.622.631A2.153 2.153 0 0 0 5 2.147c0 .568.224 1.113.622 1.515l8.249 8.34-8.25 8.34a2.16 2.16 0 0 0-.548 2.07c.196.74.768 1.317 1.499 1.515a2.104 2.104 0 0 0 2.048-.555l9.758-9.866a2.153 2.153 0 0 0 0-3.03L8.62.61C7.812-.207 6.45-.207 5.622.63z"></path></svg></h3>
254
<h3 class="ipc-title__text">Películas mejor valoradas por género</h3>
255
<h3 class="ipc-title__text">Visto recientemente</h3>
256

In [59]:
for x in soup.find_all("h3", class_="ipc-title__text")[0:25]:
    #print("Ranking:", x.get_text().split(".")[0])
    print("Título:", x.get_text())
    #print(x)

Título: Cadena perpetua
Título: El padrino
Título: El caballero oscuro
Título: El padrino parte II
Título: 12 hombres sin piedad
Título: El señor de los anillos: El retorno del rey
Título: La lista de Schindler
Título: El señor de los anillos: La comunidad del anillo
Título: Pulp Fiction
Título: El bueno, el feo y el malo
Título: El señor de los anillos: Las dos torres
Título: Forrest Gump
Título: El club de la lucha
Título: Origen
Título: El imperio contraataca
Título: Matrix
Título: Uno de los nuestros
Título: Interstellar
Título: Alguien voló sobre el nido del cuco
Título: Seven
Título: Qué bello es vivir
Título: El silencio de los corderos
Título: Los siete samuráis
Título: Salvar al soldado Ryan
Título: La milla verde

In [60]:
for x in soup.find_all("div", class_="ipc-signpost__text")[0:26]:
    #print("Ranking:", x.get_text().split(".")[0])
    print("Ranking:", int(x.get_text().replace("#","")))
    #print(x)

Ranking: 1
Ranking: 2
Ranking: 3
Ranking: 4
Ranking: 5
Ranking: 6
Ranking: 7
Ranking: 8
Ranking: 9
Ranking: 10
Ranking: 11
Ranking: 12
Ranking: 13
Ranking: 14
Ranking: 15
Ranking: 16
Ranking: 17
Ranking: 18
Ranking: 19
Ranking: 20
Ranking: 21
Ranking: 22
Ranking: 23
Ranking: 24
Ranking: 25
Ranking: 26

In [61]:
for x in soup.find_all('span', class_="ipc-rating-star--rating"):
    print("Rating:", x.get_text())

Rating: 9,3
Rating: 9,2
Rating: 9,1
Rating: 9,0
Rating: 9,0
Rating: 9,0
Rating: 9,0
Rating: 8,9
Rating: 8,8
Rating: 8,8
Rating: 8,8
Rating: 8,8
Rating: 8,8
Rating: 8,8
Rating: 8,7
Rating: 8,7
Rating: 8,7
Rating: 8,7
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,6
Rating: 8,5
Rating: 8,6
Rating: 8,6
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,8
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,6
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,4
Rating: 8,5
Rating: 8,5
Rating: 8,5
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,7
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,4
Rating: 8,3
Rating: 8,4
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,4
Rating: 8,3
Rating: 8,4
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,3
Rating: 8,2
Rating: 8,3
Rating: 8,3
Rating: 8,2
Rating: 8,2
Rating: 8,3
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,4
Rating: 8,3
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,3
Rating: 8,2
Rating: 8,3
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 9,0
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,2
Rating: 8,1
Rating: 8,4
Rating: 8,1
Rating: 8,2
Rating: 8,2
Rating: 8,4
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,2
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,2
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,4
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,2
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,3
Rating: 8,1
Rating: 8,1
Rating: 8,3
Rating: 8,6
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,0
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,2
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,1
Rating: 8,2
Rating: 8,2
Rating: 8,3

In [62]:
for x in soup.find_all("span", class_="sc-3ac6b047-6 dTZPpv cli-title-metadata-item"):
    #print(x)
    text = x.get_text()
    if len(text) == 4:
        print("Año:", text)
    if "h" in text:
        print("Duración:", text)

In [64]:
print("Ranking:", len([int(x.get_text().replace("#","")) for x in soup.find_all("div", class_="ipc-signpost__text")][0:25]))
print("Título:", len([x.get_text() for x in soup.find_all("h3", class_="ipc-title__text")][0:25]))
print("Año:", len([x.get_text() for x in soup.find_all("span", class_="sc-3ac6b047-6 dTZPpv cli-title-metadata-item") if len(x.get_text()) == 4]))
print("Duración:", len([x.get_text() for x in soup.find_all("span", class_="sc-3ac6b047-6 dTZPpv cli-title-metadata-item") if "h" in x.get_text()]))
print("Rating:", len([x.get_text() for x in soup.find_all('span', class_="ipc-rating-star--rating")]))

Ranking: 25
Título: 25
Año: 0
Duración: 0
Rating: 251

In [63]:
dict_peliculas = {"Ranking": [int(x.get_text().replace("#","")) for x in soup.find_all("div", class_="ipc-signpost__text")][0:25],
                  "Título": [x.get_text() for x in soup.find_all("h3", class_="ipc-title__text")][0:25],
                  "Año": [x.get_text() for x in soup.find_all("span", class_="sc-3ac6b047-6 dTZPpv cli-title-metadata-item") if len(x.get_text()) == 4],
                  "Duración": [x.get_text() for x in soup.find_all("span", class_="sc-3ac6b047-6 dTZPpv cli-title-metadata-item") if "h" in x.get_text()],
                  "Rating": [x.get_text() for x in soup.find_all('span', class_="ipc-rating-star--rating")]
}

df = pd.DataFrame(dict_peliculas)
df.to_csv("top25.csv")
df

ValueError: All arrays must be of the same length

In [66]:
from datetime import datetime

now = datetime.now()

print(str(now).replace(" ","_")[:16])

2026-05-13_00:36

In [67]:
import json

In [68]:
soup.find_all("script", {'type':"application/ld+json"})

[<script type="application/ld+json">{"@type":"ItemList","itemListElement":[{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0111161/","name":"The Shawshank Redemption","alternateName":"Cadena perpetua","description":"Andy Dufresne es encarcelado por matar a su esposa y al amante de esta. Tras una dura adaptación, intenta mejorar las condiciones de la prisión y dar esperanza a sus compañeros.","image":"https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.3,"ratingCount":3188156},"contentRating":"13","genre":"Drama","duration":"PT2H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0068646/","name":"The Godfather","alternateName":"El padrino","description":"El envejecido patriarca de una dinastía del crimen organizado en la ciudad de Nueva York de la posguerra transfiere el control de su imperio clandestino a su reacio hijo menor.","image":"https://m.media-amazon.com/images/M/MV5BNTljNjllNDAtMzc0MS00ZGExLThlOTktOTRlNzc3YjA3ZWFlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.2,"ratingCount":2225860},"contentRating":"18","genre":"Crimen, Drama","duration":"PT2H55M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0468569/","name":"The Dark Knight","alternateName":"El caballero oscuro","description":"Cuando la amenaza conocida como el Joker causa estragos y el caos en Gotham City, Batman debe aceptar una de las mayores pruebas psicológicas y físicas para luchar contra la injusticia.","image":"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.1,"ratingCount":3167251},"contentRating":"13","genre":"Acción, Crimen, Drama","duration":"PT2H32M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0071562/","name":"The Godfather Part II","alternateName":"El padrino parte II","description":"Se retratan los inicios de la vida y la carrera de Vito Corleone en el Nueva York de los años 20, mientras su hijo, Michael, amplía y refuerza su control sobre el sindicato del crimen familiar.","image":"https://m.media-amazon.com/images/M/MV5BMjQ5MzQxZTEtMmE1Yy00NjZlLTk5ODItNjI3MWIxMjk1M2U5XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":1495242},"contentRating":"18","genre":"Crimen, Drama","duration":"PT3H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0050083/","name":"12 Angry Men","alternateName":"12 hombres sin piedad","description":"Un miembro del jurado trata de evitar un error judicial obligando al resto del jurado a reconsiderar las pruebas.","image":"https://m.media-amazon.com/images/M/MV5BYThhOGFhODktNGEwNi00MzY2LTg3YWYtNzAzZTE0MTFlMWQxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":984164},"contentRating":"A","genre":"Crimen, Drama","duration":"PT1H36M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0167260/","name":"The Lord of the Rings: The Return of the King","alternateName":"El señor de los anillos: El retorno del rey","description":"Gandalf y Aragorn lideran el mundo de los hombres contra la armada de Sauron para distraer su atención de Frodo y Sam, quienes se aproximan al Monte del Destino con el Anillo Único.","image":"https://m.media-amazon.com/images/M/MV5BZGEzZDkzNDgtMGMzZi00NjNhLTliNWMtMTllYzQ2OTQwNGFkXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":2164401},"contentRating":"13","genre":"Aventura, Drama, Fantasía","duration":"PT3H21M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0108052/","name":"Schindler&apos;s List","alternateName":"La lista de Schindler","description":"En la Polonia ocupada por los alemanes durante la Segunda Guerra Mundial, el industrial Oskar Schindler se preocupa por sus trabajadores judíos tras presenciar su persecución por los nazis.","image":"https://m.media-amazon.com/images/M/MV5BZWUyNTJmOTMtZGM4MC00NWE2LThmZTUtZWE1NGM2YzYwZjRlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":1585446},"contentRating":"13","genre":"Biografía, Drama, Historia","duration":"PT3H15M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0120737/","name":"The Lord of the Rings: The Fellowship of the Ring","alternateName":"El señor de los anillos: La comunidad del anillo","description":"Un hobbit de la Comarca y ocho compañeros emprenden un viaje para destruir el poderoso Anillo Único y salvar la Tierra Media del Señor Oscuro Sauron.","image":"https://m.media-amazon.com/images/M/MV5BNDM0ZTRjNDAtMWFiOS00MjZiLThhZjYtNGQ0ODQ5MGE3Y2Y0XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.9,"ratingCount":2206301},"contentRating":"12","genre":"Aventura, Drama, Fantasía","duration":"PT2H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0110912/","name":"Pulp Fiction","description":"Las vidas de dos mafiosos, un boxeador, la esposa de un gánster y un par de bandidos se entrelazan en cuatro historias de violencia y redención.","image":"https://m.media-amazon.com/images/M/MV5BMzNlNGRkZWYtNmE0Yy00NjQyLWFmMzItYWY5NGM2YWU4OWYwXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2435007},"contentRating":"18","genre":"Crimen, Drama","duration":"PT2H34M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0060196/","name":"Il buono, il brutto, il cattivo","alternateName":"El bueno, el feo y el malo","description":"Durante la guerra de Secesión, tres cazarrecompensas se lanzan a la búsqueda de un tesoro que ninguno puede localizar sin la ayuda de los otros dos.","image":"https://m.media-amazon.com/images/M/MV5BN2FmNmM5OTUtODEwMC00NDE5LWI4ZTUtZTg1ZmZlYjVjN2EyXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":891409},"contentRating":"14","genre":"Aventura, Drama, Del oeste","duration":"PT3H2M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0167261/","name":"The Lord of the Rings: The Two Towers","alternateName":"El señor de los anillos: Las dos torres","description":"Mientras Frodo y Sam se acercan a Mordor con la ayuda del astuto Gollum, la comunidad dividida se enfrenta al nuevo aliado de Sauron, Saruman, y a sus hordas de Isengard.","image":"https://m.media-amazon.com/images/M/MV5BNjJhZjZlNjktZTEwYi00MmMwLTgyYTgtYmMyMmRlOWMzNmRjXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":1957114},"contentRating":"13","genre":"Aventura, Drama, Fantasía","duration":"PT2H59M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0109830/","name":"Forrest Gump","description":"Las presidencias de Kennedy y Johnson, los acontecimientos de Vietnam, el Watergate y otros eventos históricos se desarrollan a través de la perspectiva de un hombre de Alabama con un coeficiente intelectual de 75.","image":"https://m.media-amazon.com/images/M/MV5BOWQ0NzQ5MDItYTA3Yy00Y2ZjLWFlMGQtNjcxYzU4MWM3NzFmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2496357},"contentRating":"A","genre":"Drama, Romance","duration":"PT2H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0137523/","name":"Fight Club","alternateName":"El club de la lucha","description":"Un oficinista insomne y un fabricante de jabones forman un club de lucha clandestino que se convierte en mucho más.","image":"https://m.media-amazon.com/images/M/MV5BZjA1YzQ3MDktYzRjMi00NWQ0LWFhYWYtZGMyODcwNGEwZjNmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2607717},"contentRating":"18","genre":"Crimen, Drama, Suspense","duration":"PT2H19M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt1375666/","name":"Inception","alternateName":"Origen","description":"A un ladrón que roba secretos corporativos a través del uso de la tecnología de compartir sueños, se le da la tarea de implantar una idea en la mente de un jefe de una gran empresa.","image":"https://m.media-amazon.com/images/M/MV5BNTQxYmM1NzQtY2FiZS00MzRhLTljZDYtZjRmMGNiMWI3NTQxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2816580},"contentRating":"12","genre":"Acción, Aventura, Ciencia ficción","duration":"PT2H28M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0080684/","name":"Star Wars: Episode V - The Empire Strikes Back","alternateName":"El imperio contraataca","description":"Tras ser brutalmente dominados los rebeldes por el Imperio en el planeta helado Hoth, Luke Skywalker comienza su entrenamiento jedi con Yoda, mientras sus amigos son perseguidos por Darth Vader y el cazarrecompensas Boba Fett.","image":"https://m.media-amazon.com/images/M/MV5BZWQyNTJkMTAtZWQ0Zi00NGFlLWI2ZDktNTA4MzM5NDQ0MTk4XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1504924},"contentRating":"A","genre":"Acción, Aventura, Fantasía","duration":"PT2H4M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0133093/","name":"The Matrix","alternateName":"Matrix","description":"Cuando una bella desconocida lleva al hacker Neo a un inframundo prohibido, descubre la impactante verdad: la vida que conoce es un elaborado engaño de una ciberinteligencia malvada.","image":"https://m.media-amazon.com/images/M/MV5BNGE1YzI4NzMtZTUxNi00Y2I5LTg2MmQtODE0NThmYTFmMDk0XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":2247346},"contentRating":"18","genre":"Acción, Ciencia ficción","duration":"PT2H16M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0099685/","name":"GoodFellas","alternateName":"Uno de los nuestros","description":"La historia de Henry Hill y su vida en la mafia, abarcando su relación con su esposa Karen Hill y sus socios mafiosos Jimmy Conway y Tommy DeVito en el sindicato del crimen italoamericano.","image":"https://m.media-amazon.com/images/M/MV5BYTE0MmJhNGUtZDI5My00YThhLTk1NmItNDExOWUxMjg1YzUxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1391510},"contentRating":"18","genre":"Biografía, Crimen, Drama","duration":"PT2H25M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0816692/","name":"Interstellar","description":"Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.","image":"https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":2528180},"contentRating":"12","genre":"Aventura, Drama, Ciencia ficción","duration":"PT2H49M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0073486/","name":"One Flew Over the Cuckoo&apos;s Nest","alternateName":"Alguien voló sobre el nido del cuco","description":"Un criminal alega locura para ser enviado a un centro de salud mental, donde se rebela contra la opresiva enfermera y moviliza a los pacientes, a quienes tienen atemorizados.","image":"https://m.media-amazon.com/images/M/MV5BYjdkNjdlNDgtZTM1My00YzEwLTk5YjItYjE3YzllZTViNTVlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1157206},"contentRating":"18","genre":"Drama","duration":"PT2H13M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0114369/","name":"Se7en","alternateName":"Seven","description":"Dos detectives, un novato y un veterano, dan caza a un asesino en serie cuyo móvil son los siete pecados capitales.","image":"https://m.media-amazon.com/images/M/MV5BMjk4YWQ5YTItZTk2OS00MTcxLWIwNjctZjE3NzNhNjQzZjI2XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":2020713},"contentRating":"18","genre":"Crimen, Drama, Misterio","duration":"PT2H7M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0038650/","name":"It&apos;s a Wonderful Life","alternateName":"Qué bello es vivir","description":"Un ángel es enviado desde el cielo para ayudar a un hombre de negocios desesperadamente frustrado, mostrándole cómo habría sido la vida si él nunca hubiera existido.","image":"https://m.media-amazon.com/images/M/MV5BNzg5YjAwODItZmNiNC00OGEwLWIzYmMtNzc3ZTc5MmM4NDc0XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":554796},"contentRating":"A","genre":"Drama, Familiar, Fantasía","duration":"PT2H10M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0102926/","name":"The Silence of the Lambs","alternateName":"El silencio de los corderos","description":"Una joven cadete del FBI busca la ayuda de un asesino caníbal y manipulador encarcelado con el fin de atrapar a otro asesino en serie, un loco que despelleja a sus víctimas.","image":"https://m.media-amazon.com/images/M/MV5BOGZiZjYxY2UtNDE5YS00NzcwLWI0NmItNjcwYThkOWMwYTdhXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1723092},"contentRating":"18","genre":"Crimen, Drama, Terror","duration":"PT1H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0047478/","name":"Shichinin no samurai","alternateName":"Los siete samuráis","description":"Un pueblo pobre atacado por bandidos recluta a siete samuráis desempleados para que les ayuden a defenderse.","image":"https://m.media-amazon.com/images/M/MV5BYzc0ODMyMzctZTA5Zi00MGZhLWE0NTItZjJhOTE3OWMxZjBlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":401734},"contentRating":"A","genre":"Acción, Drama","duration":"PT3H27M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0120815/","name":"Saving Private Ryan","alternateName":"Salvar al soldado Ryan","description":"Tras el desembarco de Normandía, un grupo de soldados estadounidenses cruza las líneas enemigas para rescatar a un paracaidista cuyos hermanos han muerto en combate.","image":"https://m.media-amazon.com/images/M/MV5BMzU0YTgzM2EtYWNmMy00NWM1LWE0NTMtYjFhZDNlMDU1NWJmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1638907},"contentRating":"13","genre":"Drama, Bélico","duration":"PT2H49M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0120689/","name":"The Green Mile","alternateName":"La milla verde","description":"Las vidas de los guardias del corredor de la muerte se ven afectadas por uno de sus reclusos: un hombre negro acusado de asesinato y violación de niños, pero que tiene un misterioso don.","image":"https://m.media-amazon.com/images/M/MV5BM2VlMDA2NWYtYzQxZi00NGIyLTk0OTYtMGY3ODFmOGFhMTI3XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1561284},"contentRating":"13","genre":"Crimen, Drama, Fantasía","duration":"PT3H9M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0317248/","name":"Cidade de Deus","alternateName":"Ciudad de Dios","description":"En un barrio pobre de Rio, los caminos de dos niños se cruzan mientras uno quiere ser fotógrafo y el otro capo.","image":"https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":870858},"contentRating":"18","genre":"Crimen, Drama","duration":"PT2H10M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0118799/","name":"La vita è bella","alternateName":"La vida es bella","description":"Cuando un bibliotecario judío y su hijo se convierten en víctimas del Holocausto, él usará una perfecta mezcla de voluntad, humor e imaginación para proteger a su hijo de los peligros en el campo de concentración.","image":"https://m.media-amazon.com/images/M/MV5BNTZhN2IwZWUtNTI2Yy00OWNjLWExZmYtOGMzN2M5NTE1MzM1XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":812854},"contentRating":"A","genre":"Comedia, Drama, Romance","duration":"PT1H56M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0103064/","name":"Terminator 2: Judgment Day","alternateName":"Terminator 2: El juicio final","description":"Un cyborg, idéntico al que fracasó en su intento de matar a Sarah Connor, debe proteger ahora a su hijo adolescente John de un cyborg más avanzado y poderoso.","image":"https://m.media-amazon.com/images/M/MV5BM2U1MTc3M2EtYzhjYy00MmRkLWExZDEtZmI0OWNjMTFkODlmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1284075},"contentRating":"18","genre":"Acción, Aventura, Ciencia ficción","duration":"PT2H17M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0088763/","name":"Back to the Future","alternateName":"Regreso al futuro","description":"Marty McFly, un estudiante de secundaria de 17 años, es enviado accidentalmente treinta años al pasado en un DeLorean que viaja en el tiempo, inventado por su gran amigo, el excéntrico científico Doc Brown.","image":"https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.5,"ratingCount":1453004},"contentRating":"A","genre":"Aventura, Comedia, Ciencia ficción","duration":"PT1H56M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es/title/tt0076759/","name":"Star Wars","alternateName":"La guerra de las galaxias","description":"Luke Skywalker une sus fuerzas con un caballero jedi, un piloto fanfarrón, un wookiee y dos droides para salvar a la galaxia de la estación espacial del Imperio, a la vez que intenta rescatar a la princesa Leia del malvado Darth V...","image":"https://m.media-amazon.com/images/M/MV5BNGU3YTdiM2EtY2Y3MC00NTIzLWEzYzYtM2IxZDNhZjkwNjU1XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1570267},"contentRating":"A","genre":"Acción, Aventura, Fantasía","duration":"PT2H1M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/es-es

In [69]:
data = json.loads(soup.find('script', {'type':"application/ld+json"}).text)
data

{'@type': 'ItemList',
 'itemListElement': [{'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0111161/',
    'name': 'The Shawshank Redemption',
    'alternateName': 'Cadena perpetua',
    'description': 'Andy Dufresne es encarcelado por matar a su esposa y al amante de esta. Tras una dura adaptación, intenta mejorar las condiciones de la prisión y dar esperanza a sus compañeros.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.3,
     'ratingCount': 3188156},
    'contentRating': '13',
    'genre': 'Drama',
    'duration': 'PT2H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0068646/',
    'name': 'The Godfather',
    'alternateName': 'El padrino',
    'description': 'El envejecido patriarca de una dinastía del crimen organizado en la ciudad de Nueva York de la posguerra transfiere el control de su imperio clandestino a su reacio hijo menor.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNTljNjllNDAtMzc0MS00ZGExLThlOTktOTRlNzc3YjA3ZWFlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.2,
     'ratingCount': 2225860},
    'contentRating': '18',
    'genre': 'Crimen, Drama',
    'duration': 'PT2H55M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0468569/',
    'name': 'The Dark Knight',
    'alternateName': 'El caballero oscuro',
    'description': 'Cuando la amenaza conocida como el Joker causa estragos y el caos en Gotham City, Batman debe aceptar una de las mayores pruebas psicológicas y físicas para luchar contra la injusticia.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.1,
     'ratingCount': 3167251},
    'contentRating': '13',
    'genre': 'Acción, Crimen, Drama',
    'duration': 'PT2H32M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0071562/',
    'name': 'The Godfather Part II',
    'alternateName': 'El padrino parte II',
    'description': 'Se retratan los inicios de la vida y la carrera de Vito Corleone en el Nueva York de los años 20, mientras su hijo, Michael, amplía y refuerza su control sobre el sindicato del crimen familiar.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMjQ5MzQxZTEtMmE1Yy00NjZlLTk5ODItNjI3MWIxMjk1M2U5XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 1495242},
    'contentRating': '18',
    'genre': 'Crimen, Drama',
    'duration': 'PT3H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0050083/',
    'name': '12 Angry Men',
    'alternateName': '12 hombres sin piedad',
    'description': 'Un miembro del jurado trata de evitar un error judicial obligando al resto del jurado a reconsiderar las pruebas.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYThhOGFhODktNGEwNi00MzY2LTg3YWYtNzAzZTE0MTFlMWQxXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 984164},
    'contentRating': 'A',
    'genre': 'Crimen, Drama',
    'duration': 'PT1H36M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0167260/',
    'name': 'The Lord of the Rings: The Return of the King',
    'alternateName': 'El señor de los anillos: El retorno del rey',
    'description': 'Gandalf y Aragorn lideran el mundo de los hombres contra la armada de Sauron para distraer su atención de Frodo y Sam, quienes se aproximan al Monte del Destino con el Anillo Único.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZGEzZDkzNDgtMGMzZi00NjNhLTliNWMtMTllYzQ2OTQwNGFkXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 2164401},
    'contentRating': '13',
    'genre': 'Aventura, Drama, Fantasía',
    'duration': 'PT3H21M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0108052/',
    'name': 'Schindler&apos;s List',
    'alternateName': 'La lista de Schindler',
    'description': 'En la Polonia ocupada por los alemanes durante la Segunda Guerra Mundial, el industrial Oskar Schindler se preocupa por sus trabajadores judíos tras presenciar su persecución por los nazis.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZWUyNTJmOTMtZGM4MC00NWE2LThmZTUtZWE1NGM2YzYwZjRlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 1585446},
    'contentRating': '13',
    'genre': 'Biografía, Drama, Historia',
    'duration': 'PT3H15M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0120737/',
    'name': 'The Lord of the Rings: The Fellowship of the Ring',
    'alternateName': 'El señor de los anillos: La comunidad del anillo',
    'description': 'Un hobbit de la Comarca y ocho compañeros emprenden un viaje para destruir el poderoso Anillo Único y salvar la Tierra Media del Señor Oscuro Sauron.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNDM0ZTRjNDAtMWFiOS00MjZiLThhZjYtNGQ0ODQ5MGE3Y2Y0XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.9,
     'ratingCount': 2206301},
    'contentRating': '12',
    'genre': 'Aventura, Drama, Fantasía',
    'duration': 'PT2H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0110912/',
    'name': 'Pulp Fiction',
    'description': 'Las vidas de dos mafiosos, un boxeador, la esposa de un gánster y un par de bandidos se entrelazan en cuatro historias de violencia y redención.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMzNlNGRkZWYtNmE0Yy00NjQyLWFmMzItYWY5NGM2YWU4OWYwXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2435007},
    'contentRating': '18',
    'genre': 'Crimen, Drama',
    'duration': 'PT2H34M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0060196/',
    'name': 'Il buono, il brutto, il cattivo',
    'alternateName': 'El bueno, el feo y el malo',
    'description': 'Durante la guerra de Secesión, tres cazarrecompensas se lanzan a la búsqueda de un tesoro que ninguno puede localizar sin la ayuda de los otros dos.',
    'image': 'https://m.media-amazon.com/images/M/MV5BN2FmNmM5OTUtODEwMC00NDE5LWI4ZTUtZTg1ZmZlYjVjN2EyXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 891409},
    'contentRating': '14',
    'genre': 'Aventura, Drama, Del oeste',
    'duration': 'PT3H2M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0167261/',
    'name': 'The Lord of the Rings: The Two Towers',
    'alternateName': 'El señor de los anillos: Las dos torres',
    'description': 'Mientras Frodo y Sam se acercan a Mordor con la ayuda del astuto Gollum, la comunidad dividida se enfrenta al nuevo aliado de Sauron, Saruman, y a sus hordas de Isengard.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNjJhZjZlNjktZTEwYi00MmMwLTgyYTgtYmMyMmRlOWMzNmRjXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 1957114},
    'contentRating': '13',
    'genre': 'Aventura, Drama, Fantasía',
    'duration': 'PT2H59M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0109830/',
    'name': 'Forrest Gump',
    'description': 'Las presidencias de Kennedy y Johnson, los acontecimientos de Vietnam, el Watergate y otros eventos históricos se desarrollan a través de la perspectiva de un hombre de Alabama con un coeficiente intelectual de 75.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOWQ0NzQ5MDItYTA3Yy00Y2ZjLWFlMGQtNjcxYzU4MWM3NzFmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2496357},
    'contentRating': 'A',
    'genre': 'Drama, Romance',
    'duration': 'PT2H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0137523/',
    'name': 'Fight Club',
    'alternateName': 'El club de la lucha',
    'description': 'Un oficinista insomne y un fabricante de jabones forman un club de lucha clandestino que se convierte en mucho más.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZjA1YzQ3MDktYzRjMi00NWQ0LWFhYWYtZGMyODcwNGEwZjNmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2607717},
    'contentRating': '18',
    'genre': 'Crimen, Drama, Suspense',
    'duration': 'PT2H19M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt1375666/',
    'name': 'Inception',
    'alternateName': 'Origen',
    'description': 'A un ladrón que roba secretos corporativos a través del uso de la tecnología de compartir sueños, se le da la tarea de implantar una idea en la mente de un jefe de una gran empresa.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNTQxYmM1NzQtY2FiZS00MzRhLTljZDYtZjRmMGNiMWI3NTQxXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2816580},
    'contentRating': '12',
    'genre': 'Acción, Aventura, Ciencia ficción',
    'duration': 'PT2H28M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0080684/',
    'name': 'Star Wars: Episode V - The Empire Strikes Back',
    'alternateName': 'El imperio contraataca',
    'description': 'Tras ser brutalmente dominados los rebeldes por el Imperio en el planeta helado Hoth, Luke Skywalker comienza su entrenamiento jedi con Yoda, mientras sus amigos son perseguidos por Darth Vader y el cazarrecompensas Boba Fett.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZWQyNTJkMTAtZWQ0Zi00NGFlLWI2ZDktNTA4MzM5NDQ0MTk4XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1504924},
    'contentRating': 'A',
    'genre': 'Acción, Aventura, Fantasía',
    'duration': 'PT2H4M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0133093/',
    'name': 'The Matrix',
    'alternateName': 'Matrix',
    'description': 'Cuando una bella desconocida lleva al hacker Neo a un inframundo prohibido, descubre la impactante verdad: la vida que conoce es un elaborado engaño de una ciberinteligencia malvada.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNGE1YzI4NzMtZTUxNi00Y2I5LTg2MmQtODE0NThmYTFmMDk0XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 2247346},
    'contentRating': '18',
    'genre': 'Acción, Ciencia ficción',
    'duration': 'PT2H16M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0099685/',
    'name': 'GoodFellas',
    'alternateName': 'Uno de los nuestros',
    'description': 'La historia de Henry Hill y su vida en la mafia, abarcando su relación con su esposa Karen Hill y sus socios mafiosos Jimmy Conway y Tommy DeVito en el sindicato del crimen italoamericano.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYTE0MmJhNGUtZDI5My00YThhLTk1NmItNDExOWUxMjg1YzUxXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1391510},
    'contentRating': '18',
    'genre': 'Biografía, Crimen, Drama',
    'duration': 'PT2H25M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0816692/',
    'name': 'Interstellar',
    'description': 'Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 2528180},
    'contentRating': '12',
    'genre': 'Aventura, Drama, Ciencia ficción',
    'duration': 'PT2H49M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0073486/',
    'name': 'One Flew Over the Cuckoo&apos;s Nest',
    'alternateName': 'Alguien voló sobre el nido del cuco',
    'description': 'Un criminal alega locura para ser enviado a un centro de salud mental, donde se rebela contra la opresiva enfermera y moviliza a los pacientes, a quienes tienen atemorizados.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjdkNjdlNDgtZTM1My00YzEwLTk5YjItYjE3YzllZTViNTVlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1157206},
    'contentRating': '18',
    'genre': 'Drama',
    'duration': 'PT2H13M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0114369/',
    'name': 'Se7en',
    'alternateName': 'Seven',
    'description': 'Dos detectives, un novato y un veterano, dan caza a un asesino en serie cuyo móvil son los siete pecados capitales.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMjk4YWQ5YTItZTk2OS00MTcxLWIwNjctZjE3NzNhNjQzZjI2XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 2020713},
    'contentRating': '18',
    'genre': 'Crimen, Drama, Misterio',
    'duration': 'PT2H7M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0038650/',
    'name': 'It&apos;s a Wonderful Life',
    'alternateName': 'Qué bello es vivir',
    'description': 'Un ángel es enviado desde el cielo para ayudar a un hombre de negocios desesperadamente frustrado, mostrándole cómo habría sido la vida si él nunca hubiera existido.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNzg5YjAwODItZmNiNC00OGEwLWIzYmMtNzc3ZTc5MmM4NDc0XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 554796},
    'contentRating': 'A',
    'genre': 'Drama, Familiar, Fantasía',
    'duration': 'PT2H10M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0102926/',
    'name': 'The Silence of the Lambs',
    'alternateName': 'El silencio de los corderos',
    'description': 'Una joven cadete del FBI busca la ayuda de un asesino caníbal y manipulador encarcelado con el fin de atrapar a otro asesino en serie, un loco que despelleja a sus víctimas.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOGZiZjYxY2UtNDE5YS00NzcwLWI0NmItNjcwYThkOWMwYTdhXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1723092},
    'contentRating': '18',
    'genre': 'Crimen, Drama, Terror',
    'duration': 'PT1H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0047478/',
    'name': 'Shichinin no samurai',
    'alternateName': 'Los siete samuráis',
    'description': 'Un pueblo pobre atacado por bandidos recluta a siete samuráis desempleados para que les ayuden a defenderse.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYzc0ODMyMzctZTA5Zi00MGZhLWE0NTItZjJhOTE3OWMxZjBlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 401734},
    'contentRating': 'A',
    'genre': 'Acción, Drama',
    'duration': 'PT3H27M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0120815/',
    'name': 'Saving Private Ryan',
    'alternateName': 'Salvar al soldado Ryan',
    'description': 'Tras el desembarco de Normandía, un grupo de soldados estadounidenses cruza las líneas enemigas para rescatar a un paracaidista cuyos hermanos han muerto en combate.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMzU0YTgzM2EtYWNmMy00NWM1LWE0NTMtYjFhZDNlMDU1NWJmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1638907},
    'contentRating': '13',
    'genre': 'Drama, Bélico',
    'duration': 'PT2H49M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0120689/',
    'name': 'The Green Mile',
    'alternateName': 'La milla verde',
    'description': 'Las vidas de los guardias del corredor de la muerte se ven afectadas por uno de sus reclusos: un hombre negro acusado de asesinato y violación de niños, pero que tiene un misterioso don.',
    'image': 'https://m.media-amazon.com/images/M/MV5BM2VlMDA2NWYtYzQxZi00NGIyLTk0OTYtMGY3ODFmOGFhMTI3XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1561284},
    'contentRating': '13',
    'genre': 'Crimen, Drama, Fantasía',
    'duration': 'PT3H9M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0317248/',
    'name': 'Cidade de Deus',
    'alternateName': 'Ciudad de Dios',
    'description': 'En un barrio pobre de Rio, los caminos de dos niños se cruzan mientras uno quiere ser fotógrafo y el otro capo.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 870858},
    'contentRating': '18',
    'genre': 'Crimen, Drama',
    'duration': 'PT2H10M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/es-es/title/tt0118799/',
    'name': 'La vita è bella',
    'alternateName': 'La vida es bella',
    'description': 'Cuando un bibliotecario judío y su hijo se convierten en víctimas del Holocausto, él usará una perfecta mezcla de voluntad, humor e imaginación para proteger a su hijo de los peligros en el campo de concentración.',

In [70]:
data['itemListElement'][0]['item']['name']

'The Shawshank Redemption'

In [71]:
pd.DataFrame(data['itemListElement'][0]['item'])

,@type,url,name,alternateName,description,image,aggregateRating,contentRating,genre,duration
@type,Movie,https://www.imdb.com/es-es/title/tt0111161/,The Shawshank Redemption,Cadena perpetua,Andy Dufresne es encarcelado por matar a su es...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,AggregateRating,13,Drama,PT2H22M
bestRating,Movie,https://www.imdb.com/es-es/title/tt0111161/,The Shawshank Redemption,Cadena perpetua,Andy Dufresne es encarcelado por matar a su es...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,10,13,Drama,PT2H22M
worstRating,Movie,https://www.imdb.com/es-es/title/tt0111161/,The Shawshank Redemption,Cadena perpetua,Andy Dufresne es encarcelado por matar a su es...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,1,13,Drama,PT2H22M
ratingValue,Movie,https://www.imdb.com/es-es/title/tt0111161/,The Shawshank Redemption,Cadena perpetua,Andy Dufresne es encarcelado por matar a su es...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,9.3,13,Drama,PT2H22M
ratingCount,Movie,https://www.imdb.com/es-es/title/tt0111161/,The Shawshank Redemption,Cadena perpetua,Andy Dufresne es encarcelado por matar a su es...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,3188156,13,Drama,PT2H22M

In [72]:
dict_peliculas = {"Ranking": [],
                  "Título": [],
                  "Año": [],
                  "Duración": [],
                  "Rating": []
}

In [73]:
data['itemListElement'][0]['item']['duration'][2:]

'2H22M'

In [74]:
i = 1
for x in data['itemListElement']:
    print("Ranking", i)
    print("Título:", x['item'].get('name', "not found"))
    print("Rating:", x['item']['aggregateRating']['ratingValue'])
    print("Duración:", x['item']['duration'][2:])
    i = i + 1

Ranking 1
Título: The Shawshank Redemption
Rating: 9.3
Duración: 2H22M
Ranking 2
Título: The Godfather
Rating: 9.2
Duración: 2H55M
Ranking 3
Título: The Dark Knight
Rating: 9.1
Duración: 2H32M
Ranking 4
Título: The Godfather Part II
Rating: 9
Duración: 3H22M
Ranking 5
Título: 12 Angry Men
Rating: 9
Duración: 1H36M
Ranking 6
Título: The Lord of the Rings: The Return of the King
Rating: 9
Duración: 3H21M
Ranking 7
Título: Schindler&apos;s List
Rating: 9
Duración: 3H15M
Ranking 8
Título: The Lord of the Rings: The Fellowship of the Ring
Rating: 8.9
Duración: 2H58M
Ranking 9
Título: Pulp Fiction
Rating: 8.8
Duración: 2H34M
Ranking 10
Título: Il buono, il brutto, il cattivo
Rating: 8.8
Duración: 3H2M
Ranking 11
Título: The Lord of the Rings: The Two Towers
Rating: 8.8
Duración: 2H59M
Ranking 12
Título: Forrest Gump
Rating: 8.8
Duración: 2H22M
Ranking 13
Título: Fight Club
Rating: 8.8
Duración: 2H19M
Ranking 14
Título: Inception
Rating: 8.8
Duración: 2H28M
Ranking 15
Título: Star Wars: Episode V - The Empire Strikes Back
Rating: 8.7
Duración: 2H4M
Ranking 16
Título: The Matrix
Rating: 8.7
Duración: 2H16M
Ranking 17
Título: GoodFellas
Rating: 8.7
Duración: 2H25M
Ranking 18
Título: Interstellar
Rating: 8.7
Duración: 2H49M
Ranking 19
Título: One Flew Over the Cuckoo&apos;s Nest
Rating: 8.6
Duración: 2H13M
Ranking 20
Título: Se7en
Rating: 8.6
Duración: 2H7M
Ranking 21
Título: It&apos;s a Wonderful Life
Rating: 8.6
Duración: 2H10M
Ranking 22
Título: The Silence of the Lambs
Rating: 8.6
Duración: 1H58M
Ranking 23
Título: Shichinin no samurai
Rating: 8.6
Duración: 3H27M
Ranking 24
Título: Saving Private Ryan
Rating: 8.6
Duración: 2H49M
Ranking 25
Título: The Green Mile
Rating: 8.6
Duración: 3H9M
Ranking 26
Título: Cidade de Deus
Rating: 8.6
Duración: 2H10M
Ranking 27
Título: La vita è bella
Rating: 8.6
Duración: 1H56M
Ranking 28
Título: Terminator 2: Judgment Day
Rating: 8.6
Duración: 2H17M
Ranking 29
Título: Back to the Future
Rating: 8.5
Duración: 1H56M
Ranking 30
Título: Star Wars
Rating: 8.6
Duración: 2H1M
Ranking 31
Título: Sen to Chihiro no kamikakushi
Rating: 8.6
Duración: 2H4M
Ranking 32
Título: The Pianist
Rating: 8.5
Duración: 2H30M
Ranking 33
Título: Gladiator
Rating: 8.5
Duración: 2H35M
Ranking 34
Título: Gisaengchung
Rating: 8.5
Duración: 2H12M
Ranking 35
Título: Kill Bill: The Whole Bloody Affair
Rating: 8.8
Duración: 4H13M
Ranking 36
Título: Hotaru no haka
Rating: 8.5
Duración: 1H28M
Ranking 37
Título: Psycho
Rating: 8.5
Duración: 1H49M
Ranking 38
Título: The Lion King
Rating: 8.5
Duración: 1H28M
Ranking 39
Título: Seppuku
Rating: 8.6
Duración: 2H13M
Ranking 40
Título: The Departed
Rating: 8.5
Duración: 2H31M
Ranking 41
Título: Whiplash
Rating: 8.5
Duración: 1H46M
Ranking 42
Título: The Prestige
Rating: 8.5
Duración: 2H10M
Ranking 43
Título: American History X
Rating: 8.5
Duración: 1H59M
Ranking 44
Título: Léon
Rating: 8.5
Duración: 1H50M
Ranking 45
Título: Spider-Man: Across the Spider-Verse
Rating: 8.5
Duración: 2H20M
Ranking 46
Título: Nuovo Cinema Paradiso
Rating: 8.5
Duración: 2H54M
Ranking 47
Título: Casablanca
Rating: 8.5
Duración: 1H42M
Ranking 48
Título: Intouchables
Rating: 8.5
Duración: 1H52M
Ranking 49
Título: The Usual Suspects
Rating: 8.5
Duración: 1H46M
Ranking 50
Título: Django Unchained
Rating: 8.5
Duración: 2H45M
Ranking 51
Título: Alien
Rating: 8.5
Duración: 1H57M
Ranking 52
Título: Rear Window
Rating: 8.4
Duración: 1H52M
Ranking 53
Título: Modern Times
Rating: 8.5
Duración: 1H27M
Ranking 54
Título: C&apos;era una volta il West
Rating: 8.5
Duración: 2H46M
Ranking 55
Título: City Lights
Rating: 8.5
Duración: 1H27M
Ranking 56
Título: Apocalypse Now
Rating: 8.4
Duración: 2H27M
Ranking 57
Título: WALL·E
Rating: 8.4
Duración: 1H38M
Ranking 58
Título: Memento
Rating: 8.4
Duración: 1H53M
Ranking 59
Título: Dune: Part Two
Rating: 8.4
Duración: 2H46M
Ranking 60
Título: Avengers: Infinity War
Rating: 8.4
Duración: 2H29M
Ranking 61
Título: Raiders of the Lost Ark
Rating: 8.4
Duración: 1H55M
Ranking 62
Título: Das Leben der Anderen
Rating: 8.4
Duración: 2H17M
Ranking 63
Título: Spider-Man: Into the Spider-Verse
Rating: 8.4
Duración: 1H57M
Ranking 64
Título: Sunset Blvd.
Rating: 8.4
Duración: 1H50M
Ranking 65
Título: Witness for the Prosecution
Rating: 8.4
Duración: 1H56M
Ranking 66
Título: Paths of Glory
Rating: 8.4
Duración: 1H28M
Ranking 67
Título: The Shining
Rating: 8.4
Duración: 2H26M
Ranking 68
Título: The Great Dictator
Rating: 8.4
Duración: 2H5M
Ranking 69
Título: Inglourious Basterds
Rating: 8.4
Duración: 2H33M
Ranking 70
Título: 12th Fail
Rating: 8.7
Duración: 2H27M
Ranking 71
Título: Aliens
Rating: 8.4
Duración: 2H17M
Ranking 72
Título: Tengoku to jigoku
Rating: 8.4
Duración: 2H23M
Ranking 73
Título: Avengers: Endgame
Rating: 8.4
Duración: 3H1M
Ranking 74
Título: Good Will Hunting
Rating: 8.4
Duración: 2H6M
Ranking 75
Título: The Dark Knight Rises
Rating: 8.4
Duración: 2H44M
Ranking 76
Título: Coco
Rating: 8.4
Duración: 1H45M
Ranking 77
Título: Amadeus
Rating: 8.4
Duración: 2H40M
Ranking 78
Título: Toy Story
Rating: 8.3
Duración: 1H21M
Ranking 79
Título: Kimi no na wa.
Rating: 8.4
Duración: 1H46M
Ranking 80
Título: Das Boot
Rating: 8.3
Duración: 2H29M
Ranking 81
Título: Braveheart
Rating: 8.3
Duración: 2H58M
Ranking 82
Título: Oldeuboi
Rating: 8.3
Duración: 2H
Ranking 83
Título: Mononoke-hime
Rating: 8.3
Duración: 2H13M
Ranking 84
Título: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
Rating: 8.3
Duración: 1H35M
Ranking 85
Título: 3 Idiots
Rating: 8.4
Duración: 2H50M
Ranking 86
Título: American Beauty
Rating: 8.3
Duración: 2H2M
Ranking 87
Título: Capharnaüm
Rating: 8.4
Duración: 2H6M
Ranking 88
Título: Singin&apos; in the Rain
Rating: 8.3
Duración: 1H43M
Ranking 89
Título: Joker
Rating: 8.3
Duración: 2H2M
Ranking 90
Título: C&apos;era una volta in America
Rating: 8.3
Duración: 3H49M
Ranking 91
Título: Star Wars: Episode VI - Return of the Jedi
Rating: 8.3
Duración: 2H11M
Ranking 92
Título: Idi i smotri
Rating: 8.3
Duración: 2H22M
Ranking 93
Título: Requiem for a Dream
Rating: 8.3
Duración: 1H42M
Ranking 94
Título: Toy Story 3
Rating: 8.3
Duración: 1H43M
Ranking 95
Título: Ikiru
Rating: 8.3
Duración: 2H23M
Ranking 96
Título: Jagten
Rating: 8.3
Duración: 1H55M
Ranking 97
Título: Incendies
Rating: 8.3
Duración: 2H11M
Ranking 98
Título: Eternal Sunshine of the Spotless Mind
Rating: 8.3
Duración: 1H48M
Ranking 99
Título: The Apartment
Rating: 8.3
Duración: 2H5M
Ranking 100
Título: Lawrence of Arabia
Rating: 8.3
Duración: 3H47M
Ranking 101
Título: Heat
Rating: 8.3
Duración: 2H50M
Ranking 102
Título: Scarface
Rating: 8.3
Duración: 2H50M
Ranking 103
Título: Reservoir Dogs
Rating: 8.3
Duración: 1H39M
Ranking 104
Título: 2001: A Space Odyssey
Rating: 8.3
Duración: 2H29M
Ranking 105
Título: Project Hail Mary
Rating: 8.3
Duración: 2H36M
Ranking 106
Título: Up
Rating: 8.3
Duración: 1H36M
Ranking 107
Título: Double Indemnity
Rating: 8.3
Duración: 1H47M
Ranking 108
Título: North by Northwest
Rating: 8.3
Duración: 2H16M
Ranking 109
Título: Taare Zameen Par
Rating: 8.3
Duración: 2H42M
Ranking 110
Título: Full Metal Jacket
Rating: 8.2
Duración: 1H56M
Ranking 111
Título: M - Eine Stadt sucht einen Mörder
Rating: 8.3
Duración: 1H57M
Ranking 112
Título: Le fabuleux destin d&apos;Amélie Poulain
Rating: 8.3
Duración: 2H2M
Ranking 113
Título: Citizen Kane
Rating: 8.2
Duración: 1H59M
Ranking 114
Título: Vertigo
Rating: 8.2
Duración: 2H8M
Ranking 115
Título: Jodaeiye Nader az Simin
Rating: 8.3
Duración: 2H3M
Ranking 116
Título: Die Hard
Rating: 8.2
Duración: 2H12M
Ranking 117
Título: To Kill a Mockingbird
Rating: 8.2
Duración: 2H9M
Ranking 118
Título: Indiana Jones and the Last Crusade
Rating: 8.2
Duración: 2H7M
Ranking 119
Título: The Sting
Rating: 8.2
Duración: 2H9M
Ranking 120
Título: A Clockwork Orange
Rating: 8.2
Duración: 2H16M
Ranking 121
Título: Metropolis
Rating: 8.2
Duración: 2H33M
Ranking 122
Título: 1917
Rating: 8.2
Duración: 1H59M
Ranking 123
Título: Snatch
Rating: 8.2
Duración: 1H44M
Ranking 124
Título: The Wolf of Wall Street
Rating: 8.2
Duración: 3H
Ranking 125
Título: Der Untergang
Rating: 8.2
Duración: 2H36M
Ranking 126
Título: L.A. Confidential
Rating: 8.2
Duración: 2H18M
Ranking 127
Título: The Truman Show
Rating: 8.2
Duración: 1H43M
Ranking 128
Título: I Swear
Rating: 8.4
Duración: 2H
Ranking 129
Título: Dangal
Rating: 8.3
Duración: 2H41M
Ranking 130
Título: Ladri di biciclette
Rating: 8.2
Duración: 1H29M
Ranking 131
Título: Green Book
Rating: 8.2
Duración: 2H10M
Ranking 132
Título: Shutter Island
Rating: 8.2
Duración: 2H18M
Ranking 133
Título: Oppenheimer
Rating: 8.2
Duración: 3H
Ranking 134
Título: Judgment at Nuremberg
Rating: 8.3
Duración: 2H59M
Ranking 135
Título: Batman Begins
Rating: 8.2
Duración: 2H20M
Ranking 136
Título: Hamilton
Rating: 8.3
Duración: 2H40M
Ranking 137
Título: Per qualche dollaro in più
Rating: 8.2
Duración: 2H12M
Ranking 138
Título: Jurassic Park
Rating: 8.2
Duración: 2H7M
Ranking 139
Título: Taxi Driver
Rating: 8.2
Duración: 1H54M
Ranking 140
Título: Some Like It Hot
Rating: 8.2
Duración: 2H1M
Ranking 141
Título: There Will Be Blood
Rating: 8.2
Duración: 2H38M
Ranking 142
Título: The Father
Rating: 8.2
Duración: 1H37M
Ranking 143
Título: The Kid
Rating: 8.2
Duración: 1H8M
Ranking 144
Título: All About Eve
Rating: 8.2
Duración: 2H18M
Ranking 145
Título: The Sixth Sense
Rating: 8.2
Duración: 1H47M
Ranking 146
Título: Ran
Rating: 8.2
Duración: 2H40M
Ranking 147
Título: Casino
Rating: 8.2
Duración: 2H58M
Ranking 148
Título: Shingeki no Kyojin: The Last Attack
Rating: 9
Duración: 2H25M
Ranking 149
Título: No Country for Old Men
Rating: 8.2
Duración: 2H2M
Ranking 150
Título: The Thing
Rating: 8.2
Duración: 1H49M
Ranking 151
Título: Prisoners
Rating: 8.2
Duración: 2H33M
Ranking 152
Título: Top Gun: Maverick
Rating: 8.2
Duración: 2H10M
Ranking 153
Título: Kill Bill: Vol. 1
Rating: 8.2
Duración: 1H51M
Ranking 154
Título: El laberinto del fauno
Rating: 8.2
Duración: 1H58M
Ranking 155
Título: Unforgiven
Rating: 8.2
Duración: 2H10M
Ranking 156
Título: A Beautiful Mind
Rating: 8.2
Duración: 2H15M
Ranking 157
Título: Hauru no ugoku shiro
Rating: 8.2
Duración: 1H59M
Ranking 158
Título: The Treasure of the Sierra Madre
Rating: 8.2
Duración: 2H6M
Ranking 159
Título: Finding Nemo
Rating: 8.2
Duración: 1H40M
Ranking 160
Título: Klaus
Rating: 8.2
Duración: 1H36M
Ranking 161
Título: Yôjinbô
Rating: 8.2
Duración: 1H50M
Ranking 162
Título: The Great Escape
Rating: 8.2
Duración: 2H52M
Ranking 163
Título: The Elephant Man
Rating: 8.2
Duración: 2H4M
Ranking 164
Título: Monty Python and the Holy Grail
Rating: 8.1
Duración: 1H31M
Ranking 165
Título: Gekijô-ban Kimetsu no Yaiba Mugen Jô-hen
Rating: 8.4
Duración: 2H35M
Ranking 166
Título: Dial M for Murder
Rating: 8.1
Duración: 1H45M
Ranking 167
Título: El secreto de sus ojos
Rating: 8.2
Duración: 2H9M
Ranking 168
Título: Gone with the Wind
Rating: 8.2
Duración: 3H58M
Ranking 169
Título: La meglio gioventù
Rating: 8.4
Duración: 6H14M
Ranking 170
Título: Lock, Stock and Two Smoking Barrels
Rating: 8.1
Duración: 1H47M
Ranking 171
Título: Chinatown
Rating: 8.1
Duración: 2H10M
Ranking 172
Título: V for Vendetta
Rating: 8.1
Duración: 2H12M
Ranking 173
Título: Catch Me If You Can
Rating: 8.1
Duración: 2H21M
Ranking 174
Título: Inside Out
Rating: 8.1
Duración: 1H35M
Ranking 175
Título: Rashômon
Rating: 8.1
Duración: 1H28M
Ranking 176
Título: Trainspotting
Rating: 8.1
Duración: 1H33M
Ranking 177
Título: Three Billboards Outside Ebbing, Missouri
Rating: 8.1
Duración: 1H55M
Ranking 178
Título: The Bridge on the River Kwai
Rating: 8.1
Duración: 2H41M
Ranking 179
Título: Dead Poets Society
Rating: 8.1
Duración: 2H8M
Ranking 180
Título: Harry Potter and the Deathly Hallows: Part 2
Rating: 8.1
Duración: 2H10M
Ranking 181
Título: The Wild Robot
Rating: 8.2
Duración: 1H42M
Ranking 182
Título: Barry Lyndon
Rating: 8.1
Duración: 3H5M
Ranking 183
Título: Warrior
Rating: 8.1
Duración: 2H20M
Ranking 184
Título: Ben-Hur
Rating: 8.1
Duración: 3H32M
Ranking 185
Título: Fargo
Rating: 8.1
Duración: 1H38M
Ranking 186
Título: Million Dollar Baby
Rating: 8.1
Duración: 2H12M
Ranking 187
Título: Mad Max: Fury Road
Rating: 8.1
Duración: 2H
Ranking 188
Título: Hacksaw Ridge
Rating: 8.1
Duración: 2H19M
Ranking 189
Título: Bacheha-ye aseman
Rating: 8.2
Duración: 1H29M
Ranking 190
Título: Raging Bull
Rating: 8.1
Duración: 2H9M
Ranking 191
Título: Tonari no Totoro
Rating: 8.1
Duración: 1H26M
Ranking 192
Título: Gran Torino
Rating: 8.1
Duración: 1H56M
Ranking 193
Título: Ratatouille
Rating: 8.1
Duración: 1H51M
Ranking 194
Título: 12 Years a Slave
Rating: 8.1
Duración: 2H14M
Ranking 195
Título: The Grand Budapest Hotel
Rating: 8.1
Duración: 1H39M
Ranking 196
Título: Before Sunrise
Rating: 8.1
Duración: 1H41M
Ranking 197
Título: Salinui chueok
Rating: 8.1
Duración: 2H11M
Ranking 198
Título: How to Train Your Dragon
Rating: 8.1
Duración: 1H38M
Ranking 199
Título: Blade Runner
Rating: 8.1
Duración: 1H57M
Ranking 200
Título: Gone Girl
Rating: 8.1
Duración: 2H29M
Ranking 201
Título: Monsters, Inc.
Rating: 8.1
Duración: 1H32M
Ranking 202
Título: Spider-Man: No Way Home
Rating: 8.1
Duración: 2H28M
Ranking 203
Título: Hababam Sinifi: Sinifta Kaldi
Rating: 8.4
Duración: 1H35M
Ranking 204
Título: Jaws
Rating: 8.1
Duración: 2H4M
Ranking 205
Título: Ford v Ferrari
Rating: 8.1
Duración: 2H32M
Ranking 206
Título: In the Name of the Father
Rating: 8.1
Duración: 2H13M
Ranking 207
Título: Relatos salvajes
Rating: 8.1
Duración: 2H2M
Ranking 208
Título: The Gold Rush
Rating: 8.1
Duración: 1H35M
Ranking 209
Título: Sherlock Jr.
Rating: 8.1
Duración: 45M
Ranking 210
Título: Mary and Max.
Rating: 8.1
Duración: 1H32M
Ranking 211
Título: The Deer Hunter
Rating: 8.1
Duración: 3H3M
Ranking 212
Título: Le salaire de la peur
Rating: 8.1
Duración: 2H36M
Ranking 213
Título: The General
Rating: 8.1
Duración: 1H18M
Ranking 214
Título: Rocky
Rating: 8.1
Duración: 2H
Ranking 215
Título: Logan
Rating: 8.1
Duración: 2H17M
Ranking 216
Título: Mr. Smith Goes to Washington
Rating: 8.1
Duración: 2H9M
Ranking 217
Título: Pirates of the Caribbean: The Curse of the Black Pearl
Rating: 8.1
Duración: 2H23M
Ranking 218
Título: Koe no katachi
Rating: 8.2
Duración: 2H10M
Ranking 219
Título: Tôkyô monogatari
Rating: 8.1
Duración: 2H17M
Ranking 220
Título: On the Waterfront
Rating: 8.1
Duración: 1H48M
Ranking 221
Título: La haine
Rating: 8.1
Duración: 1H38M
Ranking 222
Título: Spotlight
Rating: 8.1
Duración: 2H9M
Ranking 223
Título: Smultronstället
Rating: 8.1
Duración: 1H32M
Ranking 224
Título: Gekijô-ban Chensô Man Reze-hen
Rating: 8.3
Duración: 1H40M
Ranking 225
Título: The Sound of Music
Rating: 8.1
Duración: 2H54M
Ranking 226
Título: The Terminator
Rating: 8.1
Duración: 1H47M
Ranking 227
Título: Maharaja
Rating: 8.3
Duración: 2H21M
Ranking 228
Título: Jai Bhim
Rating: 8.6
Duración: 2H44M
Ranking 229
Título: The Third Man
Rating: 8.1
Duración: 1H44M
Ranking 230
Título: The Big Lebowski
Rating: 8.1
Duración: 1H57M
Ranking 231
Título: The Best Years of Our Lives
Rating: 8.1
Duración: 2H50M
Ranking 232
Título: Before Sunset
Rating: 8.1
Duración: 1H20M
Ranking 233
Título: Room
Rating: 8.1
Duración: 1H58M
Ranking 234
Título: Det sjunde inseglet
Rating: 8.1
Duración: 1H36M
Ranking 235
Título: The Incredibles
Rating: 8
Duración: 1H55M
Ranking 236
Título: Hotel Rwanda
Rating: 8.1
Duración: 2H1M
Ranking 237
Título: Hachi: A Dog&apos;s Tale
Rating: 8.1
Duración: 1H33M
Ranking 238
Título: Platoon
Rating: 8.1
Duración: 2H
Ranking 239
Título: The Exorcist
Rating: 8.1
Duración: 2H2M
Ranking 240
Título: The Iron Giant
Rating: 8.1
Duración: 1H26M
Ranking 241
Título: Rush
Rating: 8.1
Duración: 2H3M
Ranking 242
Título: Stand by Me
Rating: 8.1
Duración: 1H29M
Ranking 243
Título: The Wizard of Oz
Rating: 8.1
Duración: 1H42M
Ranking 244
Título: Babam ve Oglum
Rating: 8.2
Duración: 1H52M
Ranking 245
Título: La battaglia di Algeri
Rating: 8.1
Duración: 2H1M
Ranking 246
Título: La passion de Jeanne d&apos;Arc
Rating: 8.1
Duración: 1H50M
Ranking 247
Título: Ah-ga-ssi
Rating: 8.1
Duración: 2H25M
Ranking 248
Título: Network
Rating: 8.1
Duración: 2H1M
Ranking 249
Título: Drishyam
Rating: 8.2
Duración: 2H43M
Ranking 250
Título: Yedinci Kogustaki Mucize
Rating: 8.2
Duración: 2H12M

In [75]:
dict_next = json.loads(soup.find("script", {'id': '__NEXT_DATA__'}).text)

In [76]:
for x in dict_next['props']['pageProps']['pageData']['chartTitles']['edges']:
    print(x['node']['releaseYear']['year'])
    print(x['currentRank'])

1994
1
1972
2
2008
3
1974
4
1957
5
2003
6
1993
7
2001
8
1994
9
1966
10
2002
11
1994
12
1999
13
2010
14
1980
15
1999
16
1990
17
2014
18
1975
19
1995
20
1946
21
1991
22
1954
23
1998
24
1999
25
2002
26
1997
27
1991
28
1985
29
1977
30
2001
31
2002
32
2000
33
2019
34
2004
35
1988
36
1960
37
1994
38
1962
39
2006
40
2014
41
2006
42
1998
43
1994
44
2023
45
1988
46
1942
47
2011
48
1995
49
2012
50
1979
51
1954
52
1936
53
1968
54
1931
55
1979
56
2008
57
2000
58
2024
59
2018
60
1981
61
2006
62
2018
63
1950
64
1957
65
1957
66
1980
67
1940
68
2009
69
2023
70
1986
71
1963
72
2019
73
1997
74
2012
75
2017
76
1984
77
1995
78
2016
79
1981
80
1995
81
2003
82
1997
83
1964
84
2009
85
1999
86
2018
87
1952
88
2019
89
1984
90
1983
91
1985
92
2000
93
2010
94
1952
95
2012
96
2010
97
2004
98
1960
99
1962
100
1995
101
1983
102
1992
103
1968
104
2026
105
2009
106
1944
107
1959
108
2007
109
1987
110
1931
111
2001
112
1941
113
1958
114
2011
115
1988
116
1962
117
1989
118
1973
119
1971
120
1927
121
2019
122
2000
123
2013
124
2004
125
1997
126
1998
127
2025
128
2016
129
1948
130
2018
131
2010
132
2023
133
1961
134
2005
135
2020
136
1965
137
1993
138
1976
139
1959
140
2007
141
2020
142
1921
143
1950
144
1999
145
1985
146
1995
147
2024
148
2007
149
1982
150
2013
151
2022
152
2003
153
2006
154
1992
155
2001
156
2004
157
1948
158
2003
159
2019
160
1961
161
1963
162
1980
163
1975
164
2025
165
1954
166
2009
167
1939
168
2003
169
1998
170
1974
171
2005
172
2002
173
2015
174
1950
175
1996
176
2017
177
1957
178
1989
179
2011
180
2024
181
1975
182
2011
183
1959
184
1996
185
2004
186
2015
187
2016
188
1997
189
1980
190
1988
191
2008
192
2007
193
2013
194
2014
195
1995
196
2003
197
2010
198
1982
199
2014
200
2001
201
2021
202
1975
203
1975
204
2019
205
1993
206
2014
207
1925
208
1924
209
2009
210
1978
211
1953
212
1926
213
1976
214
2017
215
1939
216
2003
217
2016
218
1953
219
1954
220
1995
221
2015
222
1957
223
2025
224
1965
225
1984
226
2024
227
2021
228
1949
229
1998
230
1946
231
2004
232
2015
233
1957
234
2004
235
2004
236
2009
237
1986
238
1973
239
1999
240
2013
241
1986
242
1939
243
2005
244
1966
245
1928
246
2016
247
1976
248
2015
249
2019
250

In [77]:
dict_peliculas = {"Ranking": [x['currentRank'] for x in dict_next['props']['pageProps']['pageData']['chartTitles']['edges']],
                  "Título": [x['item'].get('name', "not found") for x in data['itemListElement']],
                  "Año": [x['node']['releaseYear']['year'] for x in dict_next['props']['pageProps']['pageData']['chartTitles']['edges']],
                  "Duración": [x['item']['duration'][2:] for x in data['itemListElement']],
                  "Rating": [x['item']['aggregateRating']['ratingValue'] for x in data['itemListElement']]
}
pd.DataFrame(dict_peliculas)

     Ranking                           Título   Año Duración  Rating
0          1         The Shawshank Redemption  1994    2H22M     9.3
1          2                    The Godfather  1972    2H55M     9.2
2          3                  The Dark Knight  2008    2H32M     9.1
3          4            The Godfather Part II  1974    3H22M     9.0
4          5                     12 Angry Men  1957    1H36M     9.0
..       ...                              ...   ...      ...     ...
245      246  La passion de Jeanne d&apos;Arc  1928    1H50M     8.1
246      247                        Ah-ga-ssi  2016    2H25M     8.1
247      248                          Network  1976     2H1M     8.1
248      249                         Drishyam  2015    2H43M     8.2
249      250         Yedinci Kogustaki Mucize  2019    2H12M     8.2

[250 rows x 5 columns]