# Occupation

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"

### Step 3. Assign it to a variable called users.

In [3]:
users = pd.read_csv(url, sep="|", index_col="user_id")
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [8]:
users.groupby("occupation")["age"].mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [9]:
users.groupby("occupation")["gender"].count()

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
Name: gender, dtype: int64

In [10]:
users.groupby("gender").count()

        age  occupation  zip_code
gender
F       273         273       273
M       670         670       670

In [11]:
users["gender_n"] = (users["gender"] == "M").astype(int)
users

         age gender     occupation zip_code  gender_n
user_id
1         24      M     technician    85711         1
2         53      F          other    94043         0
3         23      M         writer    32067         1
4         24      M     technician    43537         1
5         33      F          other    15213         0
...      ...    ...            ...      ...       ...
939       26      F        student    33319         0
940       32      M  administrator    02215         1
941       20      M        student    97229         1
942       48      F      librarian    78209         0
943       22      M        student    77841         1

[943 rows x 5 columns]

In [12]:
def ratio(x):
    print("tipo de x:", type(x))
    x["ratio"] = x["gender_n"].sum() / len(x)
    return x

users = users.groupby("occupation").apply(ratio)
users

tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>
tipo de x: <class 'pandas.DataFrame'>

                       age gender zip_code  gender_n     ratio
occupation    user_id
administrator 7         57      M    91344         1  0.544304
              8         36      M    05201         1  0.544304
              34        38      F    42141         0  0.544304
              42        30      M    17870         1  0.544304
              48        45      M    12550         1  0.544304
...                    ...    ...      ...       ...       ...
writer        833       34      M    90019         1  0.577778
              842       40      M    93055         1  0.577778
              853       49      M    40515         1  0.577778
              896       28      M    91505         1  0.577778
              911       37      F    53210         0  0.577778

[943 rows x 5 columns]

In [13]:
users = users.groupby("occupation").apply(lambda x: x.assign(ratio=x["gender_n"].sum() / len(x)))
users

                                     age gender zip_code  gender_n     ratio
occupation    occupation    user_id
administrator administrator 7         57      M    91344         1  0.544304
                            8         36      M    05201         1  0.544304
                            34        38      F    42141         0  0.544304
                            42        30      M    17870         1  0.544304
                            48        45      M    12550         1  0.544304
...                                  ...    ...      ...       ...       ...
writer        writer        833       34      M    90019         1  0.577778
                            842       40      M    93055         1  0.577778
                            853       49      M    40515         1  0.577778
                            896       28      M    91505         1  0.577778
                            911       37      F    53210         0  0.577778

[943 rows x 5 columns]

In [14]:
users.groupby("occupation")["gender_n"].sum()

occupation
administrator     43
artist            15
doctor             7
educator          69
engineer          65
entertainment     16
executive         29
healthcare         5
homemaker          1
lawyer            10
librarian         22
marketing         16
none               5
other             69
programmer        60
retired           13
salesman           9
scientist         28
student          136
technician        26
writer            26
Name: gender_n, dtype: int64

In [16]:
users.groupby("occupation")["age"].count()

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
Name: age, dtype: int64

In [17]:
male_ratio = users.groupby("occupation")["gender"].apply(lambda x: (x == "M").mean() * 100).sort_values(ascending=False)
male_ratio.map(lambda x: f"{round(x, 2)}%")

occupation
doctor           100.0%
engineer         97.01%
technician        96.3%
retired          92.86%
programmer       90.91%
executive        90.62%
scientist        90.32%
entertainment    88.89%
lawyer           83.33%
salesman          75.0%
educator         72.63%
student          69.39%
other            65.71%
marketing        61.54%
writer           57.78%
none             55.56%
administrator    54.43%
artist           53.57%
librarian        43.14%
healthcare       31.25%
homemaker        14.29%
Name: gender, dtype: str

In [19]:
users.groupby("occupation")["gender"].apply(lambda x: (x == "M").mean()).sort_values(ascending=False).map(lambda x: f"{round(x*100, 2)}%")

occupation
doctor           100.0%
engineer         97.01%
technician        96.3%
retired          92.86%
programmer       90.91%
executive        90.62%
scientist        90.32%
entertainment    88.89%
lawyer           83.33%
salesman          75.0%
educator         72.63%
student          69.39%
other            65.71%
marketing        61.54%
writer           57.78%
none             55.56%
administrator    54.43%
artist           53.57%
librarian        43.14%
healthcare       31.25%
homemaker        14.29%
Name: gender, dtype: str

### Step 6. For each occupation, calculate the minimum and maximum ages

In [20]:
users.groupby("occupation")["age"].agg(["min", "max"])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [21]:
users.groupby(["occupation", "gender"])[["age"]].mean()

                            age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

### Step 8.  For each occupation present the percentage of women and men

In [22]:
users.groupby(["occupation", "gender"]).size().reset_index(name="count")

       occupation gender  count
0   administrator      F     36
1   administrator      M     43
2          artist      F     13
3          artist      M     15
4          doctor      M      7
5        educator      F     26
6        educator      M     69
7        engineer      F      2
8        engineer      M     65
9   entertainment      F      2
10  entertainment      M     16
11      executive      F      3
12      executive      M     29
13     healthcare      F     11
14     healthcare      M      5
15      homemaker      F      6
16      homemaker      M      1
17         lawyer      F      2
18         lawyer      M     10
19      librarian      F     29
20      librarian      M     22
21      marketing      F     10
22      marketing      M     16
23           none      F      4
24           none      M      5
25          other      F     36
26          other      M     69
27     programmer      F      6
28     programmer      M     60
29        retired      F      1
30        retired      M     13
31       salesman      F      3
32       salesman      M      9
33      scientist      F      3
34      scientist      M     28
35        student      F     60
36        student      M    136
37     technician      F      1
38     technician      M     26
39         writer      F     19
40         writer      M     26

In [23]:
users.groupby("occupation")["gender"].value_counts(normalize=True).mul(100).sort_values(ascending=False)

occupation     gender
doctor         M         100.000000
engineer       M          97.014925
technician     M          96.296296
retired        M          92.857143
programmer     M          90.909091
executive      M          90.625000
scientist      M          90.322581
entertainment  M          88.888889
homemaker      F          85.714286
lawyer         M          83.333333
salesman       M          75.000000
educator       M          72.631579
student        M          69.387755
healthcare     F          68.750000
other          M          65.714286
marketing      M          61.538462
writer         M          57.777778
librarian      F          56.862745
none           M          55.555556
administrator  M          54.430380
artist         M          53.571429
               F          46.428571
administrator  F          45.569620
none           F          44.444444
librarian      M          43.137255
writer         F          42.222222
marketing      F          38.461538
other          F          34.285714
healthcare     M          31.250000
student        F          30.612245
educator       F          27.368421
salesman       F          25.000000
lawyer         F          16.666667
homemaker      M          14.285714
entertainment  F          11.111111
scientist      F           9.677419
executive      F           9.375000
programmer     F           9.090909
retired        F           7.142857
technician     F           3.703704
engineer       F           2.985075
Name: proportion, dtype: float64